/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package projektSklepu;

import javax.swing.table.*;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.*; 
import java.awt.*; 
import java.awt.event.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
/**
 *
 * @author Anna Konieczna
 */
import java.util.Scanner;
public class Shops extends javax.swing.JFrame {
	
	private static final int NULL = 0;
	String url = "jdbc:mysql://localhost:3306/sklep";
	String user = "root";
	String password = "";
	

    /**
     * Creates new form Shops
     */
    public Shops() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTxtName_of_product = new javax.swing.JTextField();
        jTxTPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTxTMag_State = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxTMag_Price = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTxTMarge = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTxTProuct_Name = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTxTBought = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jButtonProd_Dodaj = new javax.swing.JButton();
        jButtonProd_Usun = new javax.swing.JButton();
        jButtonProd_Aktualizuj = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jTxT_B_Przychod = new javax.swing.JTextField();
        jTxT_B_Wydatki_stale = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTxT_B_Koszty_Pracownikuj = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTxT_B_Koszty_Dostawy = new javax.swing.JTextField();
        jTxT_B_Koszty_Dodatkowe = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTxT_B_Zysk = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTxT_B_Suma_Kosztów = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTxT_B_Straty = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTxT_B_Rentowosc = new javax.swing.JTextField();
        jButtonOblicz = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxT_P_Imie = new javax.swing.JTextField();
        jTxT_P_Nazwisko = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxT_P_Stanowisko = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxT_P_Stawka = new javax.swing.JTextField();
        jTxT_P_Godziny_Pracy = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTxT_P_Numer_Ewidencyjny = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButton_Zatrudnij = new javax.swing.JButton();
        jButton_Zwolnij = new javax.swing.JButton();
        jButton_Aktualizuj = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePracownicy = new javax.swing.JTable();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setToolTipText("Pracownicy");
        jTabbedPane1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTabbedPane1.setName("Pracownicy"); // NOI18N

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("Nazwa produktu");

        jTxtName_of_product.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTxtName_of_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtName_of_productActionPerformed(evt);
            }
        });

        jTxTPrice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setText("Cena");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setText("Stan na magazynie");

        jTxTMag_State.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setText("Koszt produktu");

        jTxTMag_Price.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel31.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel31.setText("Marża");

        jTxTMarge.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel32.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel32.setText("Numer produktu");

        jTxTProuct_Name.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel33.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel33.setText("Ilość sprzedanych");

        jTxTBought.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(430, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtName_of_product, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(jTxTPrice)
                            .addComponent(jTxTMag_State)
                            .addComponent(jTxTMag_Price)
                            .addComponent(jTxTMarge)
                            .addComponent(jTxTProuct_Name)
                            .addComponent(jTxTBought))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addContainerGap(500, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addContainerGap(421, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addContainerGap(407, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtName_of_product, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxTPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTxTMag_State, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTxTMag_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jTxTMarge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jTxTProuct_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jTxTBought, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonProd_Dodaj.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonProd_Dodaj.setText("Dodaj");
        jButtonProd_Dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProd_DodajActionPerformed(evt);
            }
        });

        jButtonProd_Usun.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonProd_Usun.setText("Usuń");
        jButtonProd_Usun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProd_UsunActionPerformed(evt);
            }
        });

        jButtonProd_Aktualizuj.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonProd_Aktualizuj.setText("Aktualizuj");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonProd_Dodaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonProd_Usun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonProd_Aktualizuj, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonProd_Dodaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonProd_Usun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonProd_Aktualizuj)
                .addGap(95, 95, 95))
        );
        
        DefaultTableModel modelpr = new DefaultTableModel(new String[]{"Id","Nazwa produktu", "Cena", "Stan na magazynie", "Koszt produktu", "Marża","Numer produktu", "Ilość sprzedanych"}, 0);
        
        try
		{
			Class.forName("com.mysql.jdbc.Driver").newInstance();
			Connection con = DriverManager.getConnection(url, user, password);
			
			Statement stt = con.createStatement();
			stt.execute("USE sklep");

	       // JTable workers = new JTable(model);
			//Create and select db
			
			ResultSet res = stt.executeQuery("SELECT * FROM  produkty");
			
			while(res.next())
			{
				Produkt produkt = new Produkt(res.getInt(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8));
				modelpr.addRow(new Object[]{produkt.getId(), produkt.getNazwa(), produkt.getCena(), produkt.getStan(), produkt.getMarza(),produkt.getKoszt(), produkt.getNumer(), produkt.getIleSprzedanych()});
			}			
			
			//System.out.println()
			res.close();
			stt.close();
			con.close();
		}
		
		catch (Exception e)
		{
			e.printStackTrace();
		}
        
        jTable2.setModel(modelpr);
        
        /*jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numer produktu", "Nazwa produktu", "Cena", "Stan na magazynie", "Koszt produktu", "Marża", "Ilość sprzedanych"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });*/
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Produkty", jPanel2);

        jPanel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel21.setText("Przychód (sprzedarz)");

        jTxT_B_Przychod.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTxT_B_Przychod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxT_B_PrzychodActionPerformed(evt);
            }
        });

        jTxT_B_Wydatki_stale.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel22.setText("Wydatki stałe");

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel23.setText("Koszty pracowników");

        jTxT_B_Koszty_Pracownikuj.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel24.setText("Koszty dostawy");

        jTxT_B_Koszty_Dostawy.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jTxT_B_Koszty_Dodatkowe.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel25.setText("Koszty dodatkowe");

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel26.setText("Zysk (prz - skoszt)");

        jTxT_B_Zysk.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel27.setText("Suma kosztów");

        jTxT_B_Suma_Kosztów.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel28.setText("Straty");

        jTxT_B_Straty.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel29.setText("Rentowność  (zysk/przych * 100 %)");

        jTxT_B_Rentowosc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jButtonOblicz.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jButtonOblicz.setText("Oblicz");
        jButtonOblicz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObliczActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel21)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxT_B_Przychod, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(jTxT_B_Wydatki_stale)
                            .addComponent(jTxT_B_Koszty_Pracownikuj)
                            .addComponent(jTxT_B_Koszty_Dostawy)
                            .addComponent(jTxT_B_Koszty_Dodatkowe)
                            .addComponent(jTxT_B_Zysk)
                            .addComponent(jTxT_B_Suma_Kosztów)
                            .addComponent(jTxT_B_Straty)
                            .addComponent(jTxT_B_Rentowosc))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 383, Short.MAX_VALUE)
                        .addComponent(jButtonOblicz, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel27))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTxT_B_Przychod, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTxT_B_Wydatki_stale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTxT_B_Koszty_Pracownikuj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTxT_B_Koszty_Dostawy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTxT_B_Koszty_Dodatkowe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTxT_B_Straty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTxT_B_Suma_Kosztów, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTxT_B_Zysk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jTxT_B_Rentowosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jButtonOblicz)
                        .addGap(29, 29, 29))))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bilans", jPanel3);

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Imię");

        jTxT_P_Imie.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTxT_P_Imie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxT_P_ImieActionPerformed(evt);
            }
        });

        jTxT_P_Nazwisko.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Nazwisko");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Pesel");

        jTxT_P_Stanowisko.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Godziny pracy");

        jTxT_P_Stawka.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTxT_P_Stawka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxT_P_StawkaActionPerformed(evt);
            }
        });

        jTxT_P_Godziny_Pracy.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Stanowisko");

        jLabel30.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel30.setText("Stawka");

        jTxT_P_Numer_Ewidencyjny.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxT_P_Imie, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxT_P_Stanowisko, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTxT_P_Nazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxT_P_Stawka, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxT_P_Godziny_Pracy, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel30)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxT_P_Numer_Ewidencyjny, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxT_P_Imie, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxT_P_Nazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxT_P_Stanowisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxT_P_Stawka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxT_P_Godziny_Pracy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jTxT_P_Numer_Ewidencyjny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton_Zatrudnij.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton_Zatrudnij.setText("Zatrudnij");
        jButton_Zatrudnij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ZatrudnijActionPerformed(evt);
            }
        });

        jButton_Zwolnij.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton_Zwolnij.setText("Zwolnij");
        jButton_Zwolnij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ZwolnijActionPerformed(evt);
            }
        });

        jButton_Aktualizuj.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton_Aktualizuj.setText("Aktualizuj");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Zatrudnij, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Zwolnij, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Aktualizuj, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Zatrudnij)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Zwolnij)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Aktualizuj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        /*jTablePracownicy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Imie", "Nazwisko", "Stanowisko", "Stawka", "Godziny pracy", "Pesel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });*/
        
        
        DefaultTableModel model = new DefaultTableModel(new String[]{"Id", "Imię", "Nazwisko","Pesel","Godziny pracy", "Stanowisko", "Stawka"}, 0);
        
        try
		{
			Class.forName("com.mysql.jdbc.Driver").newInstance();
			Connection con = DriverManager.getConnection(url, user, password);
			
			Statement stt = con.createStatement();
			stt.execute("USE sklep");

	       // JTable workers = new JTable(model);
			//Create and select db
			
			ResultSet res = stt.executeQuery("SELECT * FROM  pracownicy");
			
			while(res.next())
			{
				Pracownik pracownik = new Pracownik(res.getInt(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7));
				model.addRow(new Object[]{pracownik.getId(), pracownik.getImie(), pracownik.getNazwisko(), pracownik.getPesel(), pracownik.getDniWolne(), pracownik.getStanowisko(), pracownik.getPensja() });
			}			
			
			//System.out.println()
			res.close();
			stt.close();
			con.close();
		}
		
		catch (Exception e)
		{
			e.printStackTrace();
		}
        
        jTablePracownicy.setModel(model);
        
        jScrollPane1.setViewportView(jTablePracownicy);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pracownicy", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Pracownicy");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxT_P_ImieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxT_P_ImieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxT_P_ImieActionPerformed

    private void jTxtName_of_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtName_of_productActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtName_of_productActionPerformed

    private void jTxT_B_PrzychodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxT_B_PrzychodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxT_B_PrzychodActionPerformed

    private void jTxT_P_StawkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxT_P_StawkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxT_P_StawkaActionPerformed

    private void jButton_ZwolnijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ZwolnijActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model= (DefaultTableModel) jTablePracownicy.getModel();
        
        int column=0;
        int row = jTablePracownicy.getSelectedRow();
        String idPrac = jTablePracownicy.getModel().getValueAt(row, column).toString();
       
        model.removeRow(jTablePracownicy.getSelectedRow());
        try
        {
          // create the mysql database connection
          Class.forName("com.mysql.jdbc.Driver").newInstance();
		  Connection con = DriverManager.getConnection(url, user, password);
		  
		  Statement stt = con.createStatement();
	      stt.execute("USE sklep");
	  	      
	      stt.close();
	      
	      int idd = Integer.parseInt(idPrac);
          String query = "delete from pracownicy where id = ?";
          PreparedStatement preparedStmt = con.prepareStatement(query);
          preparedStmt.setInt(1, idd);

          // execute the preparedstatement
          preparedStmt.execute();
          
          preparedStmt.close();
          con.close();
        }
        catch (Exception e)
        {
          System.err.println("Got an exception! ");
          System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton_ZwolnijActionPerformed

    private void jButton_ZatrudnijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ZatrudnijActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model= (DefaultTableModel) jTablePracownicy.getModel();
        
   
        
            model.addRow(new Object[]{jTxT_P_Imie.getText(),
            jTxT_P_Nazwisko.getText(),jTxT_P_Stanowisko.getText(),
            jTxT_P_Stawka.getText(), jTxT_P_Godziny_Pracy.getText(), jTxT_P_Numer_Ewidencyjny.getText()});
        
            try
    		{
    			Class.forName("com.mysql.jdbc.Driver").newInstance();
    			Connection con = DriverManager.getConnection(url, user, password);
    		
    			
    			// the mysql insert statement
    		      String query = " insert into pracownicy (id, Imie, Nazwisko, PESEL, Ile_dni_wolnych, Stanowisko, Pensja)"
    		        + " values (?, ?, ?, ?, ?, ?, ?)";

    		      // create the mysql insert preparedstatement
    		      PreparedStatement preparedStmt = con.prepareStatement(query);
    		      
    		      Pracownik pracownik = new Pracownik(NULL,jTxT_P_Imie.getText(),jTxT_P_Nazwisko.getText(),jTxT_P_Numer_Ewidencyjny.getText(),jTxT_P_Godziny_Pracy.getText(),jTxT_P_Stanowisko.getText(),jTxT_P_Stawka.getText());
    		      
    		      preparedStmt.setInt(1, pracownik.getId());
    		      preparedStmt.setString (2, pracownik.getImie());
    		      preparedStmt.setString (3, pracownik.getNazwisko());
    		      preparedStmt.setString(4, pracownik.getPesel()); 
    		      preparedStmt.setString(5, pracownik.getDniWolne());  
    		      preparedStmt.setString(6, pracownik.getStanowisko());
    		      preparedStmt.setString(7, pracownik.getPensja()); 
    		      // execute the preparedstatement
    		      preparedStmt.execute();
    		      
    		      preparedStmt.close();
    		      con.close();
    		}
    		
    		catch (Exception e)
    		{
    			e.printStackTrace();
    		}
            
           
        
    }//GEN-LAST:event_jButton_ZatrudnijActionPerformed

    private void jButtonProd_DodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProd_DodajActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        
        
        
             model.addRow(new Object[]{jTxtName_of_product.getText(),
            jTxTPrice.getText(),jTxTMag_State.getText(),
            jTxTMag_Price.getText(), jTxTMarge.getText(), jTxTProuct_Name.getText(), jTxTBought.getText()});
             
             try
     		{
     			Class.forName("com.mysql.jdbc.Driver").newInstance();
     			Connection con = DriverManager.getConnection(url, user, password);
     			
     			// the mysql insert statement
     		      String query = " insert into produkty (id, Nazwa, Cena, Stan, Koszt, Marza, Numer_produktu, Ile_sprzedanych)"
     		        + " values (?, ?, ?, ?, ?, ?, ?,?)";

     		      // create the mysql insert preparedstatement
     		      
     		      Produkt produkt = new Produkt(NULL,jTxtName_of_product.getText(),jTxTPrice.getText(),jTxTMag_State.getText(),jTxTMag_Price.getText(),jTxTMarge.getText(),jTxTProuct_Name.getText(),jTxTBought.getText());
     		      PreparedStatement preparedStmt = con.prepareStatement(query);
     		      
     		      preparedStmt.setInt(1, NULL);
     		      preparedStmt.setString (2, produkt.getNazwa());
     		      preparedStmt.setString (3, produkt.getCena());
     		      preparedStmt.setString(4, produkt.getStan()); 
     		      preparedStmt.setString(5, produkt.getKoszt());  
     		      preparedStmt.setString(6,  produkt.getMarza()); 
     		      preparedStmt.setString(7,  produkt.getNumer()); 
     		      preparedStmt.setString(8,  produkt.getIleSprzedanych());
     		      // execute the preparedstatement
     		      preparedStmt.execute();
     		      
     		     preparedStmt.close();
     		     con.close();
     		}
     		
     		catch (Exception e)
     		{
     			e.printStackTrace();
     		}
        
    }//GEN-LAST:event_jButtonProd_DodajActionPerformed

    private void jButtonObliczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObliczActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonObliczActionPerformed

    private void jButtonProd_UsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProd_UsunActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model= (DefaultTableModel) jTable2.getModel();
        
        
        int column=0;
        int row = jTable2.getSelectedRow();
        
        String idProd = jTable2.getModel().getValueAt(row, column).toString();
        
        model.removeRow(jTable2.getSelectedRow());
        
        try
        {
          // create the mysql database connection
          Class.forName("com.mysql.jdbc.Driver").newInstance();
		  Connection con = DriverManager.getConnection(url, user, password);
		  
		  Statement stt = con.createStatement();
	      stt.execute("USE sklep");
	   
	      stt.close();
	   
	      int idd = Integer.parseInt(idProd);
          String query = "delete from produkty where id = ?";
          PreparedStatement preparedStmt = con.prepareStatement(query);
          
          preparedStmt.setInt(1, idd);

        
          preparedStmt.execute();
          
          preparedStmt.close();
          con.close();
        }
        catch (Exception e)
        {
          System.err.println("Got an exception! ");
          System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_jButtonProd_UsunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    	
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shops().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOblicz;
    private javax.swing.JButton jButtonProd_Aktualizuj;
    private javax.swing.JButton jButtonProd_Dodaj;
    private javax.swing.JButton jButtonProd_Usun;
    private javax.swing.JButton jButton_Aktualizuj;
    private javax.swing.JButton jButton_Zatrudnij;
    private javax.swing.JButton jButton_Zwolnij;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTablePracownicy;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTxTBought;
    private javax.swing.JTextField jTxTMag_Price;
    private javax.swing.JTextField jTxTMag_State;
    private javax.swing.JTextField jTxTMarge;
    private javax.swing.JTextField jTxTPrice;
    private javax.swing.JTextField jTxTProuct_Name;
    private javax.swing.JTextField jTxT_B_Koszty_Dodatkowe;
    private javax.swing.JTextField jTxT_B_Koszty_Dostawy;
    private javax.swing.JTextField jTxT_B_Koszty_Pracownikuj;
    private javax.swing.JTextField jTxT_B_Przychod;
    private javax.swing.JTextField jTxT_B_Rentowosc;
    private javax.swing.JTextField jTxT_B_Straty;
    private javax.swing.JTextField jTxT_B_Suma_Kosztów;
    private javax.swing.JTextField jTxT_B_Wydatki_stale;
    private javax.swing.JTextField jTxT_B_Zysk;
    private javax.swing.JTextField jTxT_P_Godziny_Pracy;
    private javax.swing.JTextField jTxT_P_Imie;
    private javax.swing.JTextField jTxT_P_Nazwisko;
    private javax.swing.JTextField jTxT_P_Numer_Ewidencyjny;
    private javax.swing.JTextField jTxT_P_Stanowisko;
    private javax.swing.JTextField jTxT_P_Stawka;
    private javax.swing.JTextField jTxtName_of_product;
    // End of variables declaration//GEN-END:variables
}
